config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :notes
  resources :lesson_days
  resources :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson_day.rb
class LessonDay < ApplicationRecord
  has_many :notes

  def order
    @lessondays.order_by
  end


end

app/models/note.rb
class Note < ApplicationRecord
  validates :student_name, presence: true
  validates :note_links, :format => URI::regexp(%w(http https))
  validates :student_info, presence: true
  validates :lesson_day, presence: true
  validates :note_topic, length: { minimum: 3, maximum: 2000 }
  validates :note_text, length: { maximum: 2000 }
  validates :note_code, length: { maximum: 2000 }

  def self.order_notes_by_creation
     order(:created_at)
   end

  belongs_to :lesson_day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/lesson_days_controller.rb
class LessonDaysController < ApplicationController
  def index
    @lessondays = LessonDay.all
  end

  def show
    @lessonday = LessonDay.find(params[:id])
  end


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all.order_notes_by_creation.reverse
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    note_params = params.require(:note).permit(:student_name, :note_topic,
    :note_text, :note_links, :note_code, :teacher_note, :student_info,
    :lesson_day_id)

    @note = Note.new(note_params)

    if @note.save
      redirect_to @note
    else
      render "new"
    end
  end

  def edit
      @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    note_params = params.require(:note).permit(:student_name, :note_topic,
    :note_text, :note_links, :note_code, :teacher_note, :student_info,
    :lesson_day_id)

    if @note.update_attributes(note_params)
      redirect_to @note
    else
      render "edit"
    end
  end

  def destroy
    @note = Note.find(params[:id])

    @note.destroy

    redirect_to notes_path
  end

  def nl2br(s)
    s.gsub(/\n/, '<br>')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lesson_days_helper.rb
module LessonDaysHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/index.html.erb
  <body id="home-page">
    <section class="banner">
      <h1> <strong>Welcome</strong></br>
        to the collaborative learning platform </br>
        for Codaisseur Academy students</br></br>
        <p class="benefits"> Share notes and code on specific classes with other students and teachers.<br/>
          Have an easy overview on both future and past lessons.<br/>
          Receive feedback from teachers in a way that all students can learn from it.

        </p>
      <span class="go_to_class"><%= link_to "Go to class!", lesson_days_path %></span>
     </h1>
    </section>



  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApp</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all',
    'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
    'data-turbolinks-track': 'reload' %>
    </style>
  </head>

  <body>

    <header>
      <%= image_tag "whiteface.png" , :class => "face_logo" %>
        <p class= "power_text"> _powered by Codaisseur </p>
      <%= link_to image_tag("whitelogo.png", :alt => "Logo", :class => "main_logo"), root_path %>

    </header>

    <div id="main_container">
      <%= yield %>
    </div>

    <footer>
      <p>Made with &#9825;
        by Maja, Robert Jan, Stefan and Tim
      </p>
    </footer>

  </body>
</html>

app/views/lesson_days/index.html.erb
<div id="flex-container">

  <section class="flex-item">
    <h2>Week 1</h2>
    <% @lessondays.each do |day| %>
      <% if day.course_week == 1 %>
      <h3><%= link_to day.subject, lesson_day_path(day.id)%></h3>
      <p><%= day.date.strftime("%A %e %B %Y") %><br>
      Teacher: <%= day.teacher%></em></p>
    <% end %>
    <% end %>
  </section>


  <section class="flex-item">
    <h2>Week 2</h2>
    <% @lessondays.each do |day| %>
      <% if day.course_week == 2 %>
      <h3><%= link_to day.subject, lesson_day_path(day.id)%></h3>
      <p><%= day.date.strftime("%A %e %B %Y") %><br>
      Teacher: <%= day.teacher%></em></p>
    <% end %>
    <% end %>
  </section>

  <section class="flex-item">
    <h2>Week 3</h2>
    <% @lessondays.each do |day| %>
      <% if day.course_week == 3 %>
      <h3><%= link_to day.subject, lesson_day_path(day.id)%></h3>
      <p><%= day.date.strftime("%A %e %B %Y") %><br>
      Teacher: <%= day.teacher%></em></p>
    <% end %>
    <% end %>
  </section>

  <section>
    <h2>Week 4</h2>
    <% @lessondays.each do |day| %>
      <% if day.course_week == 4 %>
      <h3><%= link_to day.subject, lesson_day_path(day.id)%></h3>
      <p><%= day.date.strftime("%A %e %B %Y") %><br>
      Teacher: <%= day.teacher%></em></p>
    <% end %>
    <% end %>
  </section>

  <section>
    <h2>Week 5</h2>
    <% @lessondays.each do |day| %>
      <% if day.course_week == 5 %>
      <h3><%= link_to day.subject, lesson_day_path(day.id)%></h3>
      <p><%= day.date.strftime("%A %e %B %Y") %><br>
      Teacher: <%= day.teacher%></em></p>
    <% end %>
    <% end %>
  </section>

  <section>
    <h2>Week 6</h2>
    <% @lessondays.each do |day| %>
      <% if day.course_week == 6 %>
      <h3><%= link_to day.subject, lesson_day_path(day.id)%></h3>
      <p><%= day.date.strftime("%A %e %B %Y") %><br>
      Teacher: <%= day.teacher%></em></p>
    <% end %>
    <% end %>
  </section>

  <section>
    <h2>Week 7</h2>
    <% @lessondays.each do |day| %>
      <% if day.course_week == 7 %>
      <h3><%= link_to day.subject, lesson_day_path(day.id)%></h3>
      <p><%= day.date.strftime("%A %e %B %Y") %><br>
      Teacher: <%= day.teacher%></em></p>
    <% end %>
    <% end %>
  </section>

  <section>
    <h2>Week 8</h2>
    <% @lessondays.each do |day| %>
      <% if day.course_week == 8 %>
      <h3><%= link_to day.subject, lesson_day_path(day.id)%></h3>
      <p><%= day.date.strftime("%A %e %B %Y") %><br>
      Teacher: <%= day.teacher%></em></p>
    <% end %>
    <% end %>
  </section>

</div>

app/views/lesson_days/index.html_conflict-20170113-154638.erb
<p>Test</p>

app/views/lesson_days/show.html.erb
<h2><%= @lessonday.subject%></h2>
<p>Teacher: <%= @lessonday.teacher%><br>
Date: <%= @lessonday.date.strftime("%A %e %B %Y") %></p>

<ul>
  <li>Notes</li>
<% if @lessonday.notes.any?%>
  <% @lessonday.notes.each do |note| %>
  <li><%= link_to note.note_topic, note_path(note.id) %>
    <% if note.created_at != note.updated_at %>
    updated by
    <% else %>
    created by
    <% end %>
    </body>
    </body>
    <em>written by
  <%= note.student_name %>
  <%= time_ago_in_words(note.updated_at) %> ago
</em></li>
  <% end %>
</ul>
<% else %>

<li>No notes found for this subject. </i>
<% end %>
</ul>
<p><%= link_to 'Add new note', new_note_path(@note) %></p>

<div class="navigation_tree">
  <span>>> <%= link_to 'Weeks', lesson_days_path %> >> Day</span>
</div>

app/views/notes/_form.html.erb
<style>
  body {

  }

  .form_item {
    margin-bottom: 10px;
    margin-top: 10px;
    width: 100%;
  }


  label {
    display: block;
    margin-bottom: 5px;
  }

  .small_textfield input {
    width: 80%;
  }

  #note_lesson_day_id {
    width: 80%;
  }

  .big_textfield textarea {
    width: 80%;
    min-height: 300px;
    text-align: left;
  }

  .submit_button {
        width: 100%;

  }
  .submit_button input {
    width: 80%;
    text-align: center;
    background: rgb(211, 47, 47);
    color: #eff1f7;
  }

</style>

<%= form_for @note do |f| %>

  <ul>
  <% @note.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>

  <div class="form_item">
    <%= f.label "Written by: " %>
    <span class="small_textfield"><%= f.text_field :student_name %></span>
  </div>

  <div class="form_item">
  <%= f.label "Link:" %>
  <span class="small_textfield"><%= f.text_field :note_links %></span>
  </div>

  <div class="form_item">
  <%= f.label "Student e-mail: " %>
  <span class="small_textfield"><%= f.text_field :student_info %></span>
  </div>

  <div class="form_item">
  <%= f.label "Lesson day: " %>
    <%= f.select :lesson_day_id do %>
    <% current_week = 0 %>
    <span class="small_textfield week-seperator "><%= content_tag(:option, "------ Select subject------") %></span>
      <% LessonDay.all.each do |p| %>
        <% if p.course_week != current_week %>
        <% current_week = p.course_week %>
        <span class="small_textfield week-seperator "><%= content_tag(:option, "------ Week #{p.course_week} ------") %></span>
        <% end %>
        <span class="small_textfield"><%= content_tag(:option, "#{p.date}: #{p.subject} - #{p.teacher}",
        value: p.id) %></span>
      <% end %>
    <% end %>
  </div>

  <div class="form_item">
    <%= f.label "Topic: " %>
    <span class="small_textfield"><%= f.text_field :note_topic %></span>
  </div>

  <div class="form_item">
    <%= f.label "Note:" %>
    <span class="big_textfield"><%= f.text_area :note_text, cols: "30", rows: "10" %></span>
  </div>

  <div class="form_item">
    <%= f.label "Code:" %>
    <span class="big_textfield"><%= f.text_area :note_code, cols: "30", rows: "10" %></span>
  </div>

  <div class="form_item">
    <%= f.label "Teacher's note: " if !(@note.new_record?)%>
    <span class="big_textfield"><%= f.text_area :teacher_note, cols: "30", rows: "10" if !(@note.new_record?)%></span>
  </div>
  <div class="submit_button"><%= f.submit (@note.new_record? ? "Create" : "Update") %></div>
<% end %>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>

<%= render "form" %>

<div class="navigation_tree">
  <span>>> <%= link_to 'Weeks', lesson_days_path %> >> <%= link_to 'Day', lesson_day_path(@note.lesson_day_id) %> >> <%= link_to 'Note', note_path(@note.id) %> >> Edit</span>
</div>

app/views/notes/index.html.erb
<h1>Notes</h1>

<% @notes.each do |note| %>
  <p><%= link_to note.note_topic, note_path(note.id) %> - written by <%= note.student_name %></p>
<% end %>

<%= link_to "[Create]", new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form" %>

<div class="navigation_tree">
  <span>>> <%= link_to 'Weeks', lesson_days_path %> >> New</span>
</div>

app/views/notes/show.html.erb
<style>
  ul {
    list-style-type: none;
    padding: 0;
  }

  .note_metadata li {
    margin-bottom: 3px;
  }

  .note_metadata {
    margin-bottom: 5px;
  }
  strong {
    font-size: 1.2em
  }
</style>

<h1><%= @note.note_topic %></h1>

<ul class="note_metadata">
<li><strong>Written by: </strong><%= @note.student_name %></li>
<li><strong><%= @note.student_name %>'s email: </strong><%= mail_to @note.student_info, @note.student_info  %></li>
<li><strong>Topic: </strong><%= @note.note_topic %></li>
<li><strong>Link: </strong> <%= link_to @note.note_links, @note.note_links, target: "_blank" %></li>
</ul>

<ul class="note_content">
<li><strong>Note: </strong><%= simple_format(@note.note_text) %></li>
<li><strong>Code: </strong><pre><%= @note.note_code %></pre></li>
<li><strong>Teacher's note: </strong><%= simple_format(@note.teacher_note) %></li>
</ul>

<p><%= link_to 'Edit', edit_note_path(@note.id) %> || <%= link_to 'Delete', note_path(@note.id), method: :delete, data: { confirm: "Are you sure?" } %></p>

<div class="navigation_tree">

  <span>>> <%= link_to 'Weeks', lesson_days_path %> >> <%= link_to 'Day', lesson_day_path(@note.lesson_day_id) %> >> Note</span>
</div>